import { useEffect, useMemo, useState } from "react";

const API_URL = "http://127.0.0.1:8000";
const today = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 10);
const emptyProduct = () => ({ name:"", category:"Antibiotik", manufacturer:"", supplier:"", active_ingredient:"", concentration:"", unit:"ədəd", batch_number:"", manufacture_date:"", expiry_date:"", unit_price:"", minimum_stock:"", storage_condition:"", notes:"" });
const emptyTransaction = () => ({ product_id:"", transaction_type:"Giriş", quantity:"", transaction_date:today(), unit_price:"", purpose:"", notes:"" });
const clean = (data) => Object.fromEntries(Object.entries(data).map(([k,v]) => [k, v === "" ? null : v]));

export default function DrugWarehouse({ token }) {
  const [products,setProducts]=useState([]), [transactions,setTransactions]=useState([]);
  const [productForm,setProductForm]=useState(emptyProduct()), [transactionForm,setTransactionForm]=useState(emptyTransaction());
  const [editingProduct,setEditingProduct]=useState(null), [editingTransaction,setEditingTransaction]=useState(null);
  const [photo,setPhoto]=useState(null), [message,setMessage]=useState(""), [busy,setBusy]=useState(false);
  const [filter,setFilter]=useState({ search:"", category:"", supplier:"", type:"", from:"", to:"" });
  const request=(url,options={})=>fetch(`${API_URL}${url}`,{...options,headers:{Authorization:`Bearer ${token}`,...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(options.headers||{})}});
  const load=async()=>{ try { const [p,t]=await Promise.all([request("/drug-warehouse/products"),request("/drug-warehouse/transactions")]); if(!p.ok||!t.ok) throw new Error("Məlumatlar alınmadı"); setProducts(await p.json()); setTransactions(await t.json()); } catch(e){setMessage(e.message);} };
  useEffect(()=>{load();},[]);
  const fail=async r=>{let d={};try{d=await r.json();}catch{} throw new Error(d.detail||"Əməliyyat alınmadı");};
  const saveProduct=async e=>{e.preventDefault();setBusy(true);setMessage("");try{const body=clean({...productForm,unit_price:Number(productForm.unit_price||0),minimum_stock:Number(productForm.minimum_stock||0)});const r=await request(editingProduct?`/drug-warehouse/products/${editingProduct}`:"/drug-warehouse/products",{method:editingProduct?"PUT":"POST",body:JSON.stringify(body)});if(!r.ok)await fail(r);setProductForm(emptyProduct());setEditingProduct(null);await load();setMessage("Dərman yadda saxlanıldı");}catch(e){setMessage(e.message);}finally{setBusy(false);}};
  const saveTransaction=async e=>{e.preventDefault();setBusy(true);setMessage("");try{const body=clean({...transactionForm,product_id:Number(transactionForm.product_id),quantity:Number(transactionForm.quantity),unit_price:transactionForm.unit_price===""?null:Number(transactionForm.unit_price)});const r=await request(editingTransaction?`/drug-warehouse/transactions/${editingTransaction}`:"/drug-warehouse/transactions",{method:editingTransaction?"PUT":"POST",body:JSON.stringify(body)});if(!r.ok)await fail(r);const saved=await r.json();if(photo){const form=new FormData();form.append("photo",photo);const u=await request(`/drug-warehouse/transactions/${saved.id}/document`,{method:"POST",body:form});if(!u.ok)await fail(u);}setTransactionForm(emptyTransaction());setEditingTransaction(null);setPhoto(null);await load();setMessage("Anbar əməliyyatı yadda saxlanıldı");}catch(e){setMessage(e.message);}finally{setBusy(false);}};
  const editProduct=p=>{setEditingProduct(p.id);setProductForm(Object.fromEntries(Object.keys(emptyProduct()).map(k=>[k,p[k]??""])));window.scrollTo({top:0,behavior:"smooth"});};
  const editTransaction=t=>{setEditingTransaction(t.id);setTransactionForm({product_id:String(t.product_id),transaction_type:t.transaction_type,quantity:t.quantity,transaction_date:t.transaction_date,unit_price:t.unit_price??"",purpose:t.purpose??"",notes:t.notes??""});setPhoto(null);};
  const remove=async(kind,id)=>{if(!confirm("Bu qeydi silmək istəyirsiniz?"))return;try{const r=await request(`/drug-warehouse/${kind}/${id}`,{method:"DELETE"});if(!r.ok)await fail(r);await load();setMessage("Qeyd silindi");}catch(e){setMessage(e.message);}};
  const categories=[...new Set(products.map(p=>p.category).filter(Boolean))].sort(), suppliers=[...new Set(products.map(p=>p.supplier).filter(Boolean))].sort();
  const filteredProducts=useMemo(()=>products.filter(p=>(!filter.search||`${p.name} ${p.active_ingredient||""} ${p.batch_number||""}`.toLowerCase().includes(filter.search.toLowerCase()))&&(!filter.category||p.category===filter.category)&&(!filter.supplier||p.supplier===filter.supplier)),[products,filter]);
  const filteredTransactions=useMemo(()=>transactions.filter(t=>{const p=products.find(x=>x.id===t.product_id);return (!filter.search||`${p?.name||""} ${p?.batch_number||""}`.toLowerCase().includes(filter.search.toLowerCase()))&&(!filter.category||p?.category===filter.category)&&(!filter.supplier||p?.supplier===filter.supplier)&&(!filter.type||t.transaction_type===filter.type)&&(!filter.from||t.transaction_date>=filter.from)&&(!filter.to||t.transaction_date<=filter.to)}),[transactions,products,filter]);
  const value=filteredProducts.reduce((s,p)=>s+Number(p.current_stock)*Number(p.unit_price),0), low=filteredProducts.filter(p=>Number(p.current_stock)<=Number(p.minimum_stock)).length;
  const soon=filteredProducts.filter(p=>p.expiry_date&&new Date(p.expiry_date)<=new Date(Date.now()+90*86400000)).length;
  const productName=id=>products.find(p=>p.id===id)?.name||`#${id}`;
  const productUnit=id=>products.find(p=>p.id===id)?.unit||"—";
  return <div className="drug-warehouse">
    {message&&<div className="dashboard-error">{message}</div>}
    <section className="cards"><div className="card"><span className="icon blue">💊</span><div><p>Dərman növü</p><h2>{filteredProducts.length}</h2></div></div><div className="card"><span className="icon green">₼</span><div><p>Stok dəyəri</p><h2>{value.toFixed(2)} AZN</h2></div></div><div className="card"><span className="icon orange">⚠️</span><div><p>Az qalıb</p><h2>{low}</h2></div></div><div className="card"><span className="icon purple">📅</span><div><p>90 günə bitir</p><h2>{soon}</h2></div></div></section>
    <section className="table-section mortality-form-section"><div className="section-title"><div><h2>{editingProduct?"Dərmanı redaktə et":"Yeni dərman"}</h2><p>Dərman, partiya və son istifadə məlumatları</p></div></div><form className="mortality-form" onSubmit={saveProduct}><div className="form-grid">
      <div className="form-field"><label>Dərmanın adı *</label><input value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})} required/></div><div className="form-field"><label>Kateqoriya *</label><select value={productForm.category} onChange={e=>setProductForm({...productForm,category:e.target.value})}>{["Antibiotik","Vitamin","Dezinfektant","Probiotik","Antiparazitar","Hormon","Anestezik","Digər"].map(x=><option key={x}>{x}</option>)}</select></div>
      <div className="form-field"><label>Aktiv maddə</label><input value={productForm.active_ingredient} onChange={e=>setProductForm({...productForm,active_ingredient:e.target.value})}/></div><div className="form-field"><label>Konsentrasiya</label><input value={productForm.concentration} onChange={e=>setProductForm({...productForm,concentration:e.target.value})} placeholder="Məsələn: 20%"/></div>
      <div className="form-field"><label>İstehsalçı</label><input value={productForm.manufacturer} onChange={e=>setProductForm({...productForm,manufacturer:e.target.value})}/></div><div className="form-field"><label>Təchizatçı firma</label><input value={productForm.supplier} onChange={e=>setProductForm({...productForm,supplier:e.target.value})}/></div>
      <div className="form-field"><label>Ölçü vahidi *</label><select value={productForm.unit} onChange={e=>setProductForm({...productForm,unit:e.target.value})}>{["kq","qram","litr","ml","ədəd"].map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Partiya nömrəsi</label><input value={productForm.batch_number} onChange={e=>setProductForm({...productForm,batch_number:e.target.value})}/></div>
      <div className="form-field"><label>İstehsal tarixi</label><input type="date" value={productForm.manufacture_date} onChange={e=>setProductForm({...productForm,manufacture_date:e.target.value})}/></div><div className="form-field"><label>Son istifadə tarixi</label><input type="date" value={productForm.expiry_date} onChange={e=>setProductForm({...productForm,expiry_date:e.target.value})}/></div>
      <div className="form-field"><label>Vahid qiyməti (AZN)</label><input type="number" min="0" step="0.01" value={productForm.unit_price} onChange={e=>setProductForm({...productForm,unit_price:e.target.value})}/></div><div className="form-field"><label>Minimum stok</label><input type="number" min="0" step="0.001" value={productForm.minimum_stock} onChange={e=>setProductForm({...productForm,minimum_stock:e.target.value})}/></div>
      <div className="form-field"><label>Saxlama şəraiti</label><input value={productForm.storage_condition} onChange={e=>setProductForm({...productForm,storage_condition:e.target.value})} placeholder="Məsələn: 2–8°C"/></div><div className="form-field"><label>Qeyd</label><input value={productForm.notes} onChange={e=>setProductForm({...productForm,notes:e.target.value})}/></div>
    </div><div className="form-actions">{editingProduct&&<button type="button" className="cancel-button" onClick={()=>{setEditingProduct(null);setProductForm(emptyProduct())}}>Ləğv et</button>}<button className="save-button" disabled={busy}>{busy?"Yadda saxlanılır...":"Dərmanı yadda saxla"}</button></div></form></section>
    <section className="table-section mortality-form-section"><div className="section-title"><div><h2>{editingTransaction?"Əməliyyatı redaktə et":"Anbar giriş-çıxışı"}</h2><p>Qəbul, istifadə və qaimə şəkli</p></div></div><form className="mortality-form" onSubmit={saveTransaction}><div className="form-grid">
      <div className="form-field"><label>Dərman *</label><select value={transactionForm.product_id} disabled={!!editingTransaction} onChange={e=>{const p=products.find(x=>x.id===Number(e.target.value));setTransactionForm({...transactionForm,product_id:e.target.value,unit_price:p?.unit_price??""})}} required><option value="">Seçin</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {Number(p.current_stock).toFixed(3)} {p.unit}</option>)}</select></div><div className="form-field"><label>Əməliyyat *</label><select value={transactionForm.transaction_type} onChange={e=>setTransactionForm({...transactionForm,transaction_type:e.target.value})}><option>Giriş</option><option>Çıxış</option></select></div>
      <div className="form-field"><label>Miqdar *</label><input type="number" min="0.001" step="0.001" value={transactionForm.quantity} onChange={e=>setTransactionForm({...transactionForm,quantity:e.target.value})} required/></div><div className="form-field"><label>Tarix *</label><input type="date" value={transactionForm.transaction_date} onChange={e=>setTransactionForm({...transactionForm,transaction_date:e.target.value})} required/></div>
      <div className="form-field"><label>Vahid qiyməti (AZN)</label><input type="number" min="0" step="0.01" value={transactionForm.unit_price} onChange={e=>setTransactionForm({...transactionForm,unit_price:e.target.value})}/></div><div className="form-field"><label>İstifadə məqsədi / yer</label><input value={transactionForm.purpose} onChange={e=>setTransactionForm({...transactionForm,purpose:e.target.value})} placeholder="Məsələn: Hovuz 4"/></div>
      <div className="form-field"><label>Qaimə şəkli</label><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]||null)}/><small>JPG, PNG, WEBP; maksimum 10 MB</small></div><div className="form-field"><label>Qeyd</label><input value={transactionForm.notes} onChange={e=>setTransactionForm({...transactionForm,notes:e.target.value})}/></div>
    </div><div className="form-actions">{editingTransaction&&<button type="button" className="cancel-button" onClick={()=>{setEditingTransaction(null);setTransactionForm(emptyTransaction());setPhoto(null)}}>Ləğv et</button>}<button className="save-button" disabled={busy}>Əməliyyatı yadda saxla</button></div></form></section>
    <section className="table-section"><div className="section-title"><div><h2>Filtrlər</h2><p>Dərman, firma, kateqoriya və tarix üzrə</p></div></div><div className="form-grid" style={{padding:"20px 24px"}}><div className="form-field"><label>Axtarış</label><input value={filter.search} onChange={e=>setFilter({...filter,search:e.target.value})} placeholder="Dərman, maddə və ya partiya"/></div><div className="form-field"><label>Kateqoriya</label><select value={filter.category} onChange={e=>setFilter({...filter,category:e.target.value})}><option value="">Hamısı</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Firma</label><select value={filter.supplier} onChange={e=>setFilter({...filter,supplier:e.target.value})}><option value="">Hamısı</option>{suppliers.map(x=><option key={x}>{x}</option>)}</select></div><div className="form-field"><label>Əməliyyat</label><select value={filter.type} onChange={e=>setFilter({...filter,type:e.target.value})}><option value="">Hamısı</option><option>Giriş</option><option>Çıxış</option></select></div><div className="form-field"><label>Başlanğıc tarix</label><input type="date" value={filter.from} onChange={e=>setFilter({...filter,from:e.target.value})}/></div><div className="form-field"><label>Son tarix</label><input type="date" value={filter.to} onChange={e=>setFilter({...filter,to:e.target.value})}/></div></div></section>
    <section className="table-section"><div className="section-title"><div><h2>Dərman qalığı</h2><p>Hazırkı anbar vəziyyəti</p></div></div><div style={{overflowX:"auto"}}><table><thead><tr><th>Dərman</th><th>Kateqoriya</th><th>Aktiv maddə</th><th>Firma</th><th>Partiya</th><th>Son istifadə</th><th>Qalıq</th><th>Qiymət</th><th>Dəyər</th><th>Status</th><th>Əməliyyat</th></tr></thead><tbody>{filteredProducts.map(p=>{const expired=p.expiry_date&&new Date(p.expiry_date)<new Date(), warning=p.expiry_date&&new Date(p.expiry_date)<=new Date(Date.now()+90*86400000), lowStock=Number(p.current_stock)<=Number(p.minimum_stock);return <tr key={p.id} style={{background:expired?"#fee2e2":warning||lowStock?"#fff7ed":""}}><td><strong>{p.name}</strong><br/><small>{p.concentration||""}</small></td><td>{p.category}</td><td>{p.active_ingredient||"—"}</td><td>{p.supplier||"—"}</td><td>{p.batch_number||"—"}</td><td>{p.expiry_date||"—"}</td><td><strong>{Number(p.current_stock).toFixed(3)} {p.unit}</strong></td><td>{Number(p.unit_price).toFixed(2)} AZN</td><td>{(Number(p.current_stock)*Number(p.unit_price)).toFixed(2)} AZN</td><td>{expired?"Vaxtı bitib":warning?"Tarix yaxınlaşır":lowStock?"Az qalıb":"Normal"}</td><td><div className="action-buttons"><button className="edit-button" onClick={()=>editProduct(p)}>Redaktə</button><button className="delete-button" onClick={()=>remove("products",p.id)}>Sil</button></div></td></tr>})}{!filteredProducts.length&&<tr><td colSpan="11" className="empty-row">Dərman yoxdur</td></tr>}</tbody></table></div></section>
    <section className="table-section"><div className="section-title"><div><h2>Əməliyyat tarixçəsi</h2><p>Filtr üzrə giriş və çıxışlar</p></div></div><div style={{overflowX:"auto"}}><table><thead><tr><th>Tarix</th><th>Dərman</th><th>Növ</th><th>Miqdar</th><th>Qiymət</th><th>Məbləğ</th><th>Məqsəd</th><th>Qaimə</th><th>Əməliyyat</th></tr></thead><tbody>{filteredTransactions.map(t=><tr key={t.id}><td>{t.transaction_date}</td><td><strong>{productName(t.product_id)}</strong></td><td>{t.transaction_type}</td><td>{Number(t.quantity).toFixed(3)} {productUnit(t.product_id)}</td><td>{t.unit_price==null?"—":`${Number(t.unit_price).toFixed(2)} AZN`}</td><td>{t.unit_price==null?"—":`${(Number(t.quantity)*Number(t.unit_price)).toFixed(2)} AZN`}</td><td>{t.purpose||"—"}</td><td>{t.document_path?<a href={`${API_URL}${t.document_path}`} target="_blank" rel="noreferrer"><img src={`${API_URL}${t.document_path}`} alt="Qaimə" style={{width:70,height:50,objectFit:"cover",borderRadius:6}}/></a>:"—"}</td><td><div className="action-buttons"><button className="edit-button" onClick={()=>editTransaction(t)}>Redaktə</button><button className="delete-button" onClick={()=>remove("transactions",t.id)}>Sil</button></div></td></tr>)}{!filteredTransactions.length&&<tr><td colSpan="9" className="empty-row">Əməliyyat yoxdur</td></tr>}</tbody><tfoot><tr><td colSpan="3"><strong>Filtr üzrə cəmi</strong></td><td><strong>Giriş: {filteredTransactions.filter(t=>t.transaction_type==="Giriş").reduce((s,t)=>s+Number(t.quantity),0).toFixed(3)} / Çıxış: {filteredTransactions.filter(t=>t.transaction_type==="Çıxış").reduce((s,t)=>s+Number(t.quantity),0).toFixed(3)}</strong></td><td colSpan="5"></td></tr></tfoot></table></div></section>
  </div>;
}
